#!/usr/bin/env bash
# PostToolUse hook (Edit|MultiEdit|Write): format the edited file in place.
#   api/, web/ TypeScript and JavaScript: eslint --fix (Prettier runs as an ESLint rule)
#   voice-bot/ Python: ruff format, then ruff check --fix
# Advisory: never blocks the edit. `make lint` is the pass/fail check.
set -uo pipefail

root="${CLAUDE_PROJECT_DIR:-$PWD}"
file="$(jq -r '.tool_input.file_path // empty' 2>/dev/null)"
[[ -n "$file" && -f "$file" && "$file" == "$root"/* ]] || exit 0
rel="${file#"$root"/}"

case "$rel" in
  web/src/shared/api/schema.d.ts | voice-bot/memory_bot/api/*models.py)
    # Generated by `make contracts-emit`; formatting them would break contracts-check.
    ;;
  api/*.ts | api/*.mjs | web/*.ts | web/*.tsx | web/*.js)
    eslint="$root/node_modules/.bin/eslint"
    if [[ -x "$eslint" ]]; then
      (cd "$root/${rel%%/*}" && "$eslint" --fix --no-warn-ignored "$file") >/dev/null 2>&1
    fi
    ;;
  voice-bot/*.py)
    (cd "$root/voice-bot" && uv run --no-sync ruff format --quiet "$file" \
      && uv run --no-sync ruff check --fix --quiet "$file") >/dev/null 2>&1
    ;;
esac
exit 0
